stages:
  - build
  - test

demo-job-build-code:
  stage: build
  script:
    - docker info
demo-test-code-job-first:
  stage: test
  script:
    - docker build -t localhost:5000/flask:latest .
    - docker push localhost:5000/flask:latest
